#!/usr/bin/env bash
set -ex
extra_args=($@)

if [[ ! -z "$CC" ]]; then
  extra_args+=("--use-cc=$CC")
fi

if [[ ! -z "$CXX" ]]; then
  extra_args+=("--use-c++=$CXX")
fi

scan-build --status-bugs -disable-checker deadcode.DeadStores "${extra_args[@]}" make -j4
